#!/bin/ksh
# =============================================================================
# powerha_inventory.sh
# IBM PowerHA SystemMirror — Daily Operations Inventory & Health Check
#
# Purpose  : Collect full PowerHA resource inventory, display dependency tree,
#            perform configuration health checks, emit results in structured
#            text + SVG data format, and flag any issues found.
#
# Cluster  : CL_101102  (DSB_AIX101 / DSB_AIX102)
# Version  : PowerHA SystemMirror 7.2.x
#
# Usage    : ksh /usr/local/bin/powerha_inventory.sh [-v] [-o <dir>]
#              -v   verbose mode (show all raw clmgr output)
#              -o   output directory (default: /tmp)
#
# Output   : /tmp/pha_inventory_<host>_<ts>.txt   — full text report
#            /tmp/pha_inventory_<host>_<ts>.svg    — topology SVG (generated
#                                                    by generate_svg.sh)
#            /tmp/pha_checks_<host>_<ts>.txt       — check results only
#
# Author   : PowerHA Operations
# =============================================================================

# ─────────────────────────── constants ──────────────────────────────────────
CLMGR="/usr/es/sbin/cluster/utilities/clmgr"
CLTOPINFO="/usr/es/sbin/cluster/utilities/cltopinfo"
CLDISP="/usr/es/sbin/cluster/utilities/cldisp"
CLRGINFO="/usr/es/sbin/cluster/utilities/clRGinfo"
SCRIPT_VERSION="2.0"

# ─────────────────────────── argument parsing ───────────────────────────────
VERBOSE=0
OUTPUT_DIR="/tmp"
while getopts "vo:" OPT; do
    case "${OPT}" in
        v) VERBOSE=1 ;;
        o) OUTPUT_DIR="${OPTARG}" ;;
        *) print "Usage: $0 [-v] [-o <output_dir>]" >&2; exit 1 ;;
    esac
done

# ─────────────────────────── output files ───────────────────────────────────
HOSTNAME=$(hostname)
TS=$(date "+%Y%m%d_%H%M%S")
RPT="${OUTPUT_DIR}/pha_inventory_${HOSTNAME}_${TS}.txt"
SVG_DATA="${OUTPUT_DIR}/pha_svgdata_${HOSTNAME}_${TS}.txt"
CHK="${OUTPUT_DIR}/pha_checks_${HOSTNAME}_${TS}.txt"

# ─────────────────────────── counters ───────────────────────────────────────
typeset -i CHECK_PASS=0
typeset -i CHECK_WARN=0
typeset -i CHECK_FAIL=0

# ─────────────────────────── helpers ────────────────────────────────────────
ts()      { date "+%H:%M:%S"; }
banner()  { print "\n╔══════════════════════════════════════════════════════════╗";
            printf  "║  %-56s  ║\n" "$1";
            print   "╚══════════════════════════════════════════════════════════╝"; }
section() { print "\n┌──────────────────────────────────────────────────────────┐";
            printf  "│  %-56s  │\n" "$1";
            print   "└──────────────────────────────────────────────────────────┘"; }
sub()     { print "\n  ▶ $*"; }
qval()    {
    # qval KEY "clmgr output block" → extract value for KEY=
    typeset key="$1" block="$2"
    print "${block}" | grep "^${key}=" | sed 's/^[^=]*=//;s/^"//;s/"$//'
}
chk_pass() { typeset msg="$1"; print "  [PASS] ${msg}"; print "PASS|${msg}" >> "${CHK}"; CHECK_PASS=$((CHECK_PASS+1)); }
chk_warn() { typeset msg="$1"; print "  [WARN] ${msg}"; print "WARN|${msg}" >> "${CHK}"; CHECK_WARN=$((CHECK_WARN+1)); }
chk_fail() { typeset msg="$1"; print "  [FAIL] ${msg}"; print "FAIL|${msg}" >> "${CHK}"; CHECK_FAIL=$((CHECK_FAIL+1)); }

# ─────────────────────────── preflight ──────────────────────────────────────
if [ "$(id -u)" -ne 0 ]; then
    print "ERROR: Must be run as root." >&2; exit 1
fi
if [ ! -x "${CLMGR}" ]; then
    print "ERROR: clmgr not found at ${CLMGR}. Is PowerHA installed?" >&2; exit 1
fi
mkdir -p "${OUTPUT_DIR}" 2>/dev/null

# ─────────────────────────── SVG data header ────────────────────────────────
print "# PowerHA SVG topology data — generated by powerha_inventory.sh" > "${SVG_DATA}"
print "# Format: TYPE|NAME|PARENT|DETAIL|STATE" >> "${SVG_DATA}"

# ─────────────────────────── CHECK header ───────────────────────────────────
print "# PowerHA Health Check Results — ${HOSTNAME} — $(date)" > "${CHK}"
print "# Format: RESULT|MESSAGE" >> "${CHK}"

# ═════════════════════════════════════════════════════════════════════════════
# BEGIN FULL REPORT
# ═════════════════════════════════════════════════════════════════════════════
{

banner "IBM PowerHA SystemMirror — Operations Inventory"
print "  Generated  : $(date)"
print "  Node       : ${HOSTNAME}"
print "  Script ver : ${SCRIPT_VERSION}"

# ─────────────────────────────────────────────────────────────────────────────
section "1. CLUSTER OVERVIEW"
# ─────────────────────────────────────────────────────────────────────────────

CL_RAW=$(${CLMGR} query cluster 2>/dev/null)
CL_NAME=$(qval CLUSTER_NAME  "${CL_RAW}")
CL_STATE=$(qval STATE        "${CL_RAW}")
CL_TYPE=$(qval TYPE          "${CL_RAW}")
CL_HB=$(qval HEARTBEAT_TYPE  "${CL_RAW}")
CL_VER=$(qval VERSION        "${CL_RAW}")
CL_ED=$(qval EDITION         "${CL_RAW}")
CL_REPOS=$(qval REPOSITORIES "${CL_RAW}")
CL_UNSYNC=$(qval UNSYNCED_CHANGES "${CL_RAW}")
CL_DAILY_VER=$(qval DAILY_VERIFICATION "${CL_RAW}")

print "  Cluster Name       : ${CL_NAME}"
print "  State              : ${CL_STATE}"
print "  Type               : ${CL_TYPE}"
print "  Heartbeat          : ${CL_HB}"
print "  Version            : ${CL_VER}"
print "  Edition            : ${CL_ED}"
print "  Repository Disks   : ${CL_REPOS}"
print "  Unsynced Changes   : ${CL_UNSYNC}"
print "  Daily Verification : ${CL_DAILY_VER}"

# SVG data
print "CLUSTER|${CL_NAME}||Ver:${CL_VER} HB:${CL_HB}|${CL_STATE}" >> "${SVG_DATA}"

# Checks
sub "Cluster state check"
if [ "${CL_STATE}" = "STABLE" ]; then
    chk_pass "Cluster ${CL_NAME} state is STABLE"
elif [ "${CL_STATE}" = "PENDING" ]; then
    chk_warn "Cluster ${CL_NAME} state is PENDING — monitor closely"
else
    chk_fail "Cluster ${CL_NAME} state is ${CL_STATE} — investigation required"
fi

if [ "${CL_UNSYNC}" = "true" ]; then
    chk_warn "Cluster has UNSYNCED_CHANGES=true — run clmgr sync cluster"
else
    chk_pass "No unsynced cluster changes"
fi

[ "${VERBOSE}" -eq 1 ] && { sub "Raw cluster output:"; print "${CL_RAW}"; }

# ─────────────────────────────────────────────────────────────────────────────
section "2. NODES"
# ─────────────────────────────────────────────────────────────────────────────

NODE_LIST=$(${CLMGR} query node 2>/dev/null)
print "  Nodes defined: $(print "${NODE_LIST}" | wc -l | tr -d ' ')"

for NODE in ${NODE_LIST}; do
    N_RAW=$(${CLMGR} query node "${NODE}" 2>/dev/null)
    N_STATE=$(qval STATE      "${N_RAW}")
    N_CAA=$(qval CAA_STATE    "${N_RAW}")
    N_COMM=$(qval COMMUNICATION "${N_RAW}")
    N_VER=$(qval VERSION      "${N_RAW}")
    N_AIX=$(qval AIX_LEVEL    "${N_RAW}")
    N_BOOT=$(qval START_ON_BOOT "${N_RAW}")
    N_UNSYNC=$(qval UNSYNCED_CHANGES "${N_RAW}")

    sub "Node: ${NODE}"
    print "    State          : ${N_STATE}"
    print "    CAA State      : ${N_CAA}"
    print "    Communication  : ${N_COMM}"
    print "    PowerHA Ver    : ${N_VER}"
    print "    AIX Level      : ${N_AIX}"
    print "    Start on Boot  : ${N_BOOT}"
    print "    Unsynced       : ${N_UNSYNC}"

    # SVG data
    print "NODE|${NODE}|${CL_NAME}|AIX:${N_AIX} Ver:${N_VER}|${N_STATE}" >> "${SVG_DATA}"

    # Checks
    if [ "${N_STATE}" = "NORMAL" ]; then
        chk_pass "Node ${NODE} state is NORMAL"
    else
        chk_fail "Node ${NODE} state is ${N_STATE}"
    fi
    if [ "${N_CAA}" = "UP" ]; then
        chk_pass "Node ${NODE} CAA state is UP"
    else
        chk_fail "Node ${NODE} CAA state is ${N_CAA} — check CAA subsystem"
    fi
    if [ "${N_COMM}" = "UP" ]; then
        chk_pass "Node ${NODE} communication is UP"
    else
        chk_fail "Node ${NODE} communication is ${N_COMM}"
    fi
    if [ "${N_BOOT}" = "true" ]; then
        chk_pass "Node ${NODE} START_ON_BOOT is enabled"
    else
        chk_warn "Node ${NODE} START_ON_BOOT is disabled — cluster won't auto-start after reboot"
    fi
    if [ "${N_UNSYNC}" = "true" ]; then
        chk_warn "Node ${NODE} has UNSYNCED_CHANGES"
    fi

    [ "${VERBOSE}" -eq 1 ] && { sub "Raw node output (${NODE}):"; print "${N_RAW}"; }
done

# ─────────────────────────────────────────────────────────────────────────────
section "3. NETWORKS"
# ─────────────────────────────────────────────────────────────────────────────

NET_LIST=$(${CLMGR} query network 2>/dev/null)
print "  Networks defined: $(print "${NET_LIST}" | wc -l | tr -d ' ')"

for NET in ${NET_LIST}; do
    N_RAW=$(${CLMGR} query network "${NET}" 2>/dev/null)
    N_MASK=$(qval NETMASK     "${N_RAW}")
    N_TYPE=$(qval TYPE        "${N_RAW}")
    N_BOOT=$(qval BOOT_ADAPTERS  "${N_RAW}")
    N_SVC=$(qval SERVICE_ADAPTERS "${N_RAW}")
    N_MON=$(qval MONITOR_METHOD  "${N_RAW}")

    sub "Network: ${NET}"
    print "    Type           : ${N_TYPE}"
    print "    Netmask        : ${N_MASK}"
    print "    Boot Adapters  : ${N_BOOT}"
    print "    Svc Adapters   : ${N_SVC}"
    print "    Monitor Method : ${N_MON}"

    print "NETWORK|${NET}|${CL_NAME}|Type:${N_TYPE} Mask:${N_MASK}|UP" >> "${SVG_DATA}"

    # Checks
    if [ "${N_BOOT}" -ge 2 ] 2>/dev/null; then
        chk_pass "Network ${NET} has ${N_BOOT} boot adapters (redundant)"
    elif [ "${N_BOOT}" -eq 1 ] 2>/dev/null; then
        chk_warn "Network ${NET} has only 1 boot adapter — single point of failure"
    fi

    [ "${VERBOSE}" -eq 1 ] && { sub "Raw network output (${NET}):"; print "${N_RAW}"; }
done

# ─────────────────────────────────────────────────────────────────────────────
section "4. INTERFACES (IP LABELS)"
# ─────────────────────────────────────────────────────────────────────────────

IFACE_LIST=$(${CLMGR} query interface 2>/dev/null)
print "  Interfaces defined: $(print "${IFACE_LIST}" | wc -l | tr -d ' ')"

for IFACE in ${IFACE_LIST}; do
    I_RAW=$(${CLMGR} query interface "${IFACE}" 2>/dev/null)
    I_IP=$(qval IPADDR    "${I_RAW}")
    I_STATE=$(qval STATE  "${I_RAW}")
    I_TYPE=$(qval TYPE    "${I_RAW}")
    I_NET=$(qval NETWORK  "${I_RAW}")
    I_NODE=$(qval NODE    "${I_RAW}")
    I_IF=$(qval INTERFACE "${I_RAW}")

    sub "Interface: ${IFACE}"
    print "    IP Address     : ${I_IP}"
    print "    State          : ${I_STATE}"
    print "    Type           : ${I_TYPE}  (boot=node-bound / service=floating)"
    print "    Network        : ${I_NET}"
    print "    Node           : ${I_NODE}"
    print "    AIX Interface  : ${I_IF}"

    print "INTERFACE|${IFACE}|${I_NODE}|IP:${I_IP} Net:${I_NET} Type:${I_TYPE}|${I_STATE}" >> "${SVG_DATA}"

    # Checks
    if [ "${I_STATE}" = "UP" ]; then
        chk_pass "Interface ${IFACE} (${I_IP}) state is UP"
    else
        chk_fail "Interface ${IFACE} (${I_IP}) state is ${I_STATE}"
    fi

    [ "${VERBOSE}" -eq 1 ] && { sub "Raw interface output (${IFACE}):"; print "${I_RAW}"; }
done

# ─────────────────────────────────────────────────────────────────────────────
section "5. RESOURCE GROUPS"
# ─────────────────────────────────────────────────────────────────────────────

RG_LIST=$(${CLMGR} query resource_group 2>/dev/null)
print "  Resource groups defined: $(print "${RG_LIST}" | wc -l | tr -d ' ')"

for RG in ${RG_LIST}; do
    RG_RAW=$(${CLMGR} query resource_group "${RG}" 2>/dev/null)
    RG_STATE=$(qval STATE          "${RG_RAW}")
    RG_NODE=$(qval CURRENT_NODE    "${RG_RAW}")
    RG_NODES=$(qval NODES          "${RG_RAW}")
    RG_TYPE=$(qval TYPE            "${RG_RAW}")
    RG_STARTUP=$(qval STARTUP      "${RG_RAW}")
    RG_FALLOVER=$(qval FALLOVER    "${RG_RAW}")
    RG_FALLBACK=$(qval FALLBACK    "${RG_RAW}")
    RG_APPS=$(qval APPLICATIONS    "${RG_RAW}")
    RG_SVC=$(qval SERVICE_LABEL    "${RG_RAW}")
    RG_VG=$(qval VOLUME_GROUP      "${RG_RAW}")
    RG_FS=$(qval FILESYSTEM        "${RG_RAW}")
    RG_FORCED=$(qval FORCED_VARYON "${RG_RAW}")
    RG_INACTIVE=$(qval INACTIVE_TAKEOVER "${RG_RAW}")

    # Translate policy codes
    case "${RG_STARTUP}" in
        OHN)  RG_STARTUP_H="Online On Home Node Only" ;;
        OFAN) RG_STARTUP_H="Online On First Available Node" ;;
        ONS)  RG_STARTUP_H="Online On All Available Nodes" ;;
        *)    RG_STARTUP_H="${RG_STARTUP}" ;;
    esac
    case "${RG_FALLOVER}" in
        FNPN) RG_FALLOVER_H="Fallover To Next Priority Node" ;;
        FUDNL) RG_FALLOVER_H="Fallover Using Dynamic Node List" ;;
        NOFM) RG_FALLOVER_H="No Fallover — Notify Only" ;;
        *)    RG_FALLOVER_H="${RG_FALLOVER}" ;;
    esac
    case "${RG_FALLBACK}" in
        NFB)  RG_FALLBACK_H="Never Fallback" ;;
        FBHPN) RG_FALLBACK_H="Fallback To Higher Priority Node" ;;
        *)    RG_FALLBACK_H="${RG_FALLBACK}" ;;
    esac

    sub "Resource Group: ${RG}"
    print "    State            : ${RG_STATE}"
    print "    Current Node     : ${RG_NODE}"
    print "    Priority Nodes   : ${RG_NODES}"
    print "    Type             : ${RG_TYPE}"
    print "    Startup Policy   : ${RG_STARTUP_H}"
    print "    Fallover Policy  : ${RG_FALLOVER_H}"
    print "    Fallback Policy  : ${RG_FALLBACK_H}"
    print "    Application(s)   : ${RG_APPS}"
    print "    Service Label    : ${RG_SVC}"
    print "    Volume Group(s)  : ${RG_VG}"
    print "    File Systems     : ${RG_FS}"
    print "    Forced VaryOn    : ${RG_FORCED}"
    print "    Inactive Takeover: ${RG_INACTIVE}"

    print "RG|${RG}|${CL_NAME}|Node:${RG_NODE} VG:${RG_VG} SVC:${RG_SVC}|${RG_STATE}" >> "${SVG_DATA}"

    # Checks
    if [ "${RG_STATE}" = "ONLINE" ]; then
        chk_pass "Resource group ${RG} is ONLINE on ${RG_NODE}"
    elif [ "${RG_STATE}" = "OFFLINE" ]; then
        chk_warn "Resource group ${RG} is OFFLINE — intended?"
    else
        chk_fail "Resource group ${RG} is in state ${RG_STATE}"
    fi
    if [ "${RG_FORCED}" = "true" ]; then
        chk_warn "RG ${RG}: FORCED_VARYON=true — data integrity risk if disk not clean"
    fi
    if [ "${RG_INACTIVE}" = "true" ]; then
        chk_warn "RG ${RG}: INACTIVE_TAKEOVER=true — RG may come online on inactive node"
    fi
    if [ -z "${RG_APPS}" ]; then
        chk_warn "RG ${RG}: No application controller assigned"
    fi
    if [ -z "${RG_VG}" ]; then
        chk_warn "RG ${RG}: No volume group assigned"
    fi

    [ "${VERBOSE}" -eq 1 ] && { sub "Raw RG output (${RG}):"; print "${RG_RAW}"; }
done

# ─────────────────────────────────────────────────────────────────────────────
section "6. SERVICE IP LABELS"
# ─────────────────────────────────────────────────────────────────────────────

SVC_LIST=$(${CLMGR} query service_ip 2>/dev/null)
for SVC in ${SVC_LIST}; do
    S_RAW=$(${CLMGR} query service_ip "${SVC}" 2>/dev/null)
    S_IP=$(qval IPADDR   "${S_RAW}")
    S_NODE=$(qval NODE   "${S_RAW}")
    S_NET=$(qval NETWORK "${S_RAW}")
    S_MASK=$(qval NETMASK "${S_RAW}")

    sub "Service IP: ${SVC}"
    print "    IP Address     : ${S_IP}"
    print "    Active Node    : ${S_NODE}"
    print "    Network        : ${S_NET}"
    print "    Netmask        : ${S_MASK}"

    print "SERVICEIP|${SVC}|${SVC}|IP:${S_IP} Node:${S_NODE}|UP" >> "${SVG_DATA}"
done

# ─────────────────────────────────────────────────────────────────────────────
section "7. APPLICATION CONTROLLERS"
# ─────────────────────────────────────────────────────────────────────────────

APP_LIST=$(${CLMGR} query application 2>/dev/null)
for APP in ${APP_LIST}; do
    A_RAW=$(${CLMGR} query application "${APP}" 2>/dev/null)
    A_START=$(qval STARTSCRIPT   "${A_RAW}")
    A_STOP=$(qval STOPSCRIPT     "${A_RAW}")
    A_CPU=$(qval CPU_USAGE_MONITOR "${A_RAW}")
    A_MODE=$(qval STARTUP_MODE   "${A_RAW}")
    A_MON=$(qval MONITORING_STATUS "${A_RAW}")
    A_RG=$(qval RESOURCE_GROUP   "${A_RAW}")

    sub "Application Controller: ${APP}"
    print "    Resource Group : ${A_RG}"
    print "    Start Script   : ${A_START}"
    print "    Stop Script    : ${A_STOP}"
    print "    Startup Mode   : ${A_MODE}"
    print "    CPU Monitor    : ${A_CPU}"
    print "    Monitor Status : ${A_MON}"

    print "APP|${APP}|${A_RG}|Start:${A_START} Stop:${A_STOP}|${A_MON}" >> "${SVG_DATA}"

    # Checks
    if [ -n "${A_START}" ] && [ -f "${A_START}" ]; then
        chk_pass "App ${APP}: Start script exists: ${A_START}"
    elif [ -n "${A_START}" ]; then
        chk_fail "App ${APP}: Start script NOT FOUND: ${A_START}"
    else
        chk_warn "App ${APP}: No start script defined"
    fi
    if [ -n "${A_STOP}" ] && [ -f "${A_STOP}" ]; then
        chk_pass "App ${APP}: Stop script exists: ${A_STOP}"
    elif [ -n "${A_STOP}" ]; then
        chk_fail "App ${APP}: Stop script NOT FOUND: ${A_STOP}"
    else
        chk_warn "App ${APP}: No stop script defined"
    fi
    if [ "${A_MON}" = "NOT_MONITORED" ]; then
        chk_warn "App ${APP}: Application monitoring is NOT configured"
    fi

    [ "${VERBOSE}" -eq 1 ] && { sub "Raw app output (${APP}):"; print "${A_RAW}"; }
done

# ─────────────────────────────────────────────────────────────────────────────
section "8. VOLUME GROUPS"
# ─────────────────────────────────────────────────────────────────────────────

VG_LIST=$(${CLMGR} query volume_group 2>/dev/null)
for VG in ${VG_LIST}; do
    V_RAW=$(${CLMGR} query volume_group "${VG}" 2>/dev/null)
    V_TYPE=$(qval TYPE        "${V_RAW}")
    V_NODES=$(qval NODES      "${V_RAW}")
    V_LVS=$(qval LOGICAL_VOLUMES "${V_RAW}")
    V_PVS=$(qval PHYSICAL_VOLUMES "${V_RAW}")
    V_RG=$(qval RESOURCE_GROUP   "${V_RAW}")
    V_SCSI=$(qval SCSIPR_CAPABLE "${V_RAW}")
    V_CRITICAL=$(qval CRITICAL   "${V_RAW}")

    # LVM details
    VG_LVM=$(lsvg "${VG}" 2>/dev/null)
    VG_STATE=$(print "${VG_LVM}" | grep "VG STATE:"  | sed 's/.*VG STATE:[[:space:]]*//' | awk '{print $1}')
    VG_TOTAL=$(print "${VG_LVM}" | grep "TOTAL PPs:" | sed 's/.*TOTAL PPs:[[:space:]]*//' | awk '{print $1}')
    VG_FREE=$(print "${VG_LVM}"  | grep "FREE PPs:"  | sed 's/.*FREE PPs:[[:space:]]*//'  | awk '{print $1}')
    VG_USED=$(print "${VG_LVM}"  | grep "USED PPs:"  | sed 's/.*USED PPs:[[:space:]]*//'  | awk '{print $1}')
    VG_STALE=$(print "${VG_LVM}" | grep "STALE PPs:" | sed 's/.*STALE PPs:[[:space:]]*//' | awk '{print $1}')

    sub "Volume Group: ${VG}"
    print "    Resource Group : ${V_RG}"
    print "    VG Type        : ${V_TYPE}"
    print "    Nodes          : ${V_NODES}"
    print "    LVM State      : ${VG_STATE}"
    print "    SCSIPR Capable : ${V_SCSI}"
    print "    Critical VG    : ${V_CRITICAL}"
    print "    Total PPs      : ${VG_TOTAL}   Free: ${VG_FREE}   Used: ${VG_USED}   Stale: ${VG_STALE}"
    print "    Logical Vols   : ${V_LVS}"
    print "    Physical Vols  : ${V_PVS}"

    print "VG|${VG}|${V_RG}|Type:${V_TYPE} PVs:${V_PVS}|${VG_STATE}" >> "${SVG_DATA}"

    # Checks
    if [ "${VG_STATE}" = "active" ]; then
        chk_pass "VG ${VG} is active"
    else
        chk_fail "VG ${VG} state is ${VG_STATE}"
    fi
    if [ "${VG_STALE}" != "0" ] && [ -n "${VG_STALE}" ]; then
        chk_fail "VG ${VG} has STALE PPs: ${VG_STALE} — mirror sync required"
    else
        chk_pass "VG ${VG} has no stale PPs"
    fi
    if [ "${V_SCSI}" = "Yes" ]; then
        chk_pass "VG ${VG} is SCSIPR capable (disk fencing supported)"
    else
        chk_warn "VG ${VG} is not SCSIPR capable — disk fencing not available"
    fi

    # Logical volumes
    sub "  Logical Volumes in ${VG}:"
    lsvg -l "${VG}" 2>/dev/null | while read LV TYPE LPS PPS PVS LV_STATE MP; do
        print "    ${LV}  type=${TYPE}  LPs=${LPS}  state=${LV_STATE}  mount=${MP}"
        print "LV|${LV}|${VG}|Type:${TYPE} LPs:${LPS} Mount:${MP}|${LV_STATE}" >> "${SVG_DATA}"
        # Check for open/stale state
        case "${LV_STATE}" in
            *stale*) chk_fail "LV ${LV} in VG ${VG} has stale partitions" ;;
            closed*) chk_warn "LV ${LV} in VG ${VG} is closed — not mounted?" ;;
        esac
    done

    # Physical volumes
    sub "  Physical Volumes in ${VG}:"
    lsvg -p "${VG}" 2>/dev/null | grep -v "^${VG}:" | grep -v "^PV_NAME" | \
    while read PV PV_STATE TOTAL FREE DIST; do
        [ -z "${PV}" ] && continue
        print "    ${PV}  state=${PV_STATE}  total=${TOTAL}  free=${FREE}"
        print "PV|${PV}|${VG}|State:${PV_STATE} Total:${TOTAL} Free:${FREE}|${PV_STATE}" >> "${SVG_DATA}"
        if [ "${PV_STATE}" != "active" ]; then
            chk_fail "PV ${PV} in VG ${VG} state is ${PV_STATE}"
        fi
    done

    [ "${VERBOSE}" -eq 1 ] && { sub "Raw VG output (${VG}):"; print "${V_RAW}"; }
done

# ─────────────────────────────────────────────────────────────────────────────
section "9. FILE SYSTEMS"
# ─────────────────────────────────────────────────────────────────────────────

FS_LIST=$(${CLMGR} query file_system 2>/dev/null)
if [ -n "${FS_LIST}" ]; then
    for FS in ${FS_LIST}; do
        F_RAW=$(${CLMGR} query file_system "${FS}" 2>/dev/null)
        sub "File System: ${FS}"
        print "${F_RAW}"
        print "FS|${FS}|unknown|clmgr|DEFINED" >> "${SVG_DATA}"
    done
else
    sub "No file systems explicitly defined in PowerHA (mounted via ALL FS in RG)"
fi

# Show mounted shared filesystems from df
sub "Shared Filesystem Mount Status (from df -g):"
print "  $(printf '%-20s %-10s %-10s %-6s %s' 'Filesystem' 'Size(GB)' 'Free(GB)' '%Used' 'MountPt')"
print "  $(printf '%-20s %-10s %-10s %-6s %s' '──────────' '────────' '────────' '─────' '───────')"
df -g 2>/dev/null | grep -v "^Filesystem\|^/proc\|^/aha" | while read FS_DEV GB_BLK FREE PUSED IUSED PIUSED MP; do
    case "${MP}" in
        /sharefs*|/data*|/app*|/db*)
            print "  $(printf '%-20s %-10s %-10s %-6s %s' "${FS_DEV}" "${GB_BLK}" "${FREE}" "${PUSED}" "${MP}")"
            print "FS|${MP}|VG_SHARED|Size:${GB_BLK}GB Free:${FREE}GB|${PUSED}" >> "${SVG_DATA}"
            # Alert on high usage
            PNUM=$(print "${PUSED}" | tr -d '%')
            if [ "${PNUM}" -ge 90 ] 2>/dev/null; then
                chk_fail "Filesystem ${MP} usage is ${PUSED} — CRITICAL"
            elif [ "${PNUM}" -ge 80 ] 2>/dev/null; then
                chk_warn "Filesystem ${MP} usage is ${PUSED} — approaching threshold"
            else
                chk_pass "Filesystem ${MP} usage is ${PUSED}"
            fi
            ;;
    esac
done

# ─────────────────────────────────────────────────────────────────────────────
section "10. REPOSITORY & HEARTBEAT DISKS"
# ─────────────────────────────────────────────────────────────────────────────

sub "CAA Repository Disks:"
REPO_OUT=$(${CLMGR} query repository 2>/dev/null)
print "  ${REPO_OUT}"
# Join multiline repo output into single line for SVG data record
REPO_SINGLE=$(print "${REPO_OUT}" | tr '\n' ' ' | sed 's/  */ /g;s/ $//')
print "REPO|CAA_REPOSITORY|${CL_NAME}|${REPO_SINGLE}|active" >> "${SVG_DATA}"

REPO_COUNT=$(print "${REPO_OUT}" | wc -l | tr -d ' ')
if [ "${REPO_COUNT}" -ge 2 ]; then
    chk_pass "CAA has ${REPO_COUNT} repository disks (redundant)"
elif [ "${REPO_COUNT}" -eq 1 ]; then
    chk_warn "CAA has only 1 repository disk — consider adding a second for redundancy"
else
    chk_fail "No CAA repository disk found — cluster CAA may be degraded"
fi

sub "Disk Heartbeat Disks:"
HB_LIST=$(${CLMGR} query disk 2>/dev/null)
if [ -n "${HB_LIST}" ]; then
    for HBDISK in $(print "${HB_LIST}" | awk '{print $1}'); do
        D_RAW=$(${CLMGR} query disk "${HBDISK}" 2>/dev/null)
        D_VG=$(qval VOLUME_GROUP  "${D_RAW}")
        D_TYPE=$(qval TYPE        "${D_RAW}")
        D_SIZE=$(qval SIZE        "${D_RAW}")
        D_STATUS=$(qval STATUS    "${D_RAW}")
        D_SCSI=$(qval SCSIPR_CAPABLE "${D_RAW}")
        print "  ${HBDISK}: VG=${D_VG}  Type=${D_TYPE}  Size=${D_SIZE}MB  Status=${D_STATUS}  SCSIPR=${D_SCSI}"
        print "HB_DISK|${HBDISK}|${CL_NAME}|VG:${D_VG} Size:${D_SIZE}MB|${D_STATUS}" >> "${SVG_DATA}"
        if [ "${D_STATUS}" = "Available" ]; then
            chk_pass "Heartbeat disk ${HBDISK} is Available"
        else
            chk_fail "Heartbeat disk ${HBDISK} status is ${D_STATUS}"
        fi
    done
else
    sub "No dedicated disk heartbeat disks configured"
fi

# ─────────────────────────────────────────────────────────────────────────────
section "11. RUNTIME STATE"
# ─────────────────────────────────────────────────────────────────────────────

sub "Resource Group States (clRGinfo):"
${CLRGINFO} 2>/dev/null

sub "Cluster Services (lssrc -g cluster):"
lssrc -g cluster 2>/dev/null | while read SUBSYS GRP PID STATUS; do
    [ "${SUBSYS}" = "Subsystem" ] && continue
    print "  ${SUBSYS}  PID=${PID}  Status=${STATUS}"
    if [ "${STATUS}" = "active" ]; then
        chk_pass "Cluster daemon ${SUBSYS} is active (PID ${PID})"
    else
        chk_fail "Cluster daemon ${SUBSYS} is NOT active (Status: ${STATUS})"
    fi
done

sub "Active Volume Groups (lsvg -o):"
lsvg -o 2>/dev/null | while read VGO; do
    print "  ${VGO}"
done

sub "Network Interface Addresses (ifconfig -a):"
ifconfig -a 2>/dev/null | grep "inet " | while read DUMMY IP REST; do
    print "  ${IP}"
done

# ─────────────────────────────────────────────────────────────────────────────
section "12. DEPENDENCY TREE"
# ─────────────────────────────────────────────────────────────────────────────

print ""
print "  Cluster: ${CL_NAME}  [${CL_STATE}]"
print "  │"

for NODE in $(${CLMGR} query node 2>/dev/null); do
    print "  ├── Node: ${NODE}"
    for NET in $(${CLMGR} query network 2>/dev/null); do
        print "  │   ├── Network: ${NET}"
        # show interfaces on this node + this network
        for IFACE in $(${CLMGR} query interface 2>/dev/null); do
            I_RAW=$(${CLMGR} query interface "${IFACE}" 2>/dev/null)
            I_NODE=$(qval NODE    "${I_RAW}")
            I_NET=$(qval NETWORK  "${I_RAW}")
            I_IP=$(qval IPADDR    "${I_RAW}")
            I_TYPE=$(qval TYPE    "${I_RAW}")
            I_STATE=$(qval STATE  "${I_RAW}")
            if [ "${I_NODE}" = "${NODE}" ] && [ "${I_NET}" = "${NET}" ]; then
                print "  │   │   └── [${I_TYPE}] ${IFACE}  ${I_IP}  (${I_STATE})"
            fi
        done
    done
done

print "  │"
print "  └── Resource Groups:"

for RG in $(${CLMGR} query resource_group 2>/dev/null); do
    RG_RAW=$(${CLMGR} query resource_group "${RG}" 2>/dev/null)
    RG_STATE=$(qval STATE        "${RG_RAW}")
    RG_NODE=$(qval CURRENT_NODE  "${RG_RAW}")
    RG_APPS=$(qval APPLICATIONS  "${RG_RAW}")
    RG_SVC=$(qval SERVICE_LABEL  "${RG_RAW}")
    RG_VG=$(qval VOLUME_GROUP    "${RG_RAW}")
    print "      ├── RG: ${RG}  [${RG_STATE} on ${RG_NODE}]"
    print "      │   ├── Service IP   : ${RG_SVC}"
    # Service IP details
    S_RAW=$(${CLMGR} query service_ip "${RG_SVC}" 2>/dev/null)
    S_IP=$(qval IPADDR "${S_RAW}")
    print "      │   │     └── IP: ${S_IP}"
    print "      │   ├── Application  : ${RG_APPS}"
    # App details
    A_RAW=$(${CLMGR} query application "${RG_APPS}" 2>/dev/null)
    A_START=$(qval STARTSCRIPT "${A_RAW}")
    A_STOP=$(qval STOPSCRIPT   "${A_RAW}")
    print "      │   │     ├── Start: ${A_START}"
    print "      │   │     └── Stop : ${A_STOP}"
    print "      │   └── Volume Group : ${RG_VG}"
    # VG → LV → FS
    lsvg -l "${RG_VG}" 2>/dev/null | grep -v "^${RG_VG}:" | grep -v "^LV NAME" | \
    while read LV TYPE LPS PPS PVS LV_STATE MP; do
        [ -z "${LV}" ] && continue
        print "      │         ├── LV: ${LV}  [${LV_STATE}]  → ${MP}"
    done
    # PVs
    lsvg -p "${RG_VG}" 2>/dev/null | grep -v "^${RG_VG}:" | grep -v "^PV_NAME" | \
    while read PV PV_STATE TOTAL FREE DIST; do
        [ -z "${PV}" ] && continue
        print "      │         └── PV: ${PV}  [${PV_STATE}]  Total:${TOTAL}PP  Free:${FREE}PP"
    done
    print "      │"
done

# ─────────────────────────────────────────────────────────────────────────────
section "13. ERROR LOG REVIEW"
# ─────────────────────────────────────────────────────────────────────────────

sub "Recent AIX error log (errpt — last 30 lines):"
errpt 2>/dev/null | head -30

sub "Check for critical cluster-related errors:"
CRITICAL_ERRS=$(errpt 2>/dev/null | grep -i -E "fscsi|cluster|hacmp|caa|CAA" | wc -l | tr -d ' ')
if [ "${CRITICAL_ERRS}" -gt 5 ]; then
    chk_warn "Found ${CRITICAL_ERRS} cluster/storage related entries in errpt — review advised"
else
    chk_pass "Error log has ${CRITICAL_ERRS} cluster/storage entries (within normal range)"
fi

# ─────────────────────────────────────────────────────────────────────────────
section "14. INSTALLED FILESETS"
# ─────────────────────────────────────────────────────────────────────────────

sub "PowerHA filesets (COMMITTED only):"
lslpp -l "cluster.*" 2>/dev/null | grep COMMITTED | \
    awk '{printf "  %-40s %s\n", $1, $2}' | sort -u

# Version consistency check
VER_COUNT=$(lslpp -l "cluster.es.server.rte" 2>/dev/null | grep COMMITTED | awk '{print $2}' | sort -u | wc -l | tr -d ' ')
if [ "${VER_COUNT}" -eq 1 ]; then
    chk_pass "PowerHA server fileset version is consistent across objrepos"
else
    chk_warn "Multiple PowerHA server fileset versions detected — check lslpp output"
fi

# ─────────────────────────────────────────────────────────────────────────────
section "15. SYSTEM INFORMATION"
# ─────────────────────────────────────────────────────────────────────────────

sub "AIX Level:"
print "  $(oslevel -s 2>/dev/null)"

sub "Hardware:"
prtconf 2>/dev/null | head -6 | while read LINE; do print "  ${LINE}"; done

sub "Uptime:"
print "  $(uptime 2>/dev/null)"

# ─────────────────────────────────────────────────────────────────────────────
section "16. HEALTH CHECK SUMMARY"
# ─────────────────────────────────────────────────────────────────────────────

typeset -i TOTAL_CHK=$((CHECK_PASS + CHECK_WARN + CHECK_FAIL))
print ""
print "  ┌─────────────────────────────────────────┐"
print "  │         HEALTH CHECK RESULTS            │"
print "  ├─────────────────────────────────────────┤"
printf  "  │  %-38s │\n" "Total Checks : ${TOTAL_CHK}"
printf  "  │  %-38s │\n" "PASS         : ${CHECK_PASS}"
printf  "  │  %-38s │\n" "WARN         : ${CHECK_WARN}"
printf  "  │  %-38s │\n" "FAIL         : ${CHECK_FAIL}"
print "  └─────────────────────────────────────────┘"

if [ "${CHECK_FAIL}" -gt 0 ]; then
    print ""
    print "  *** FAILED CHECKS ***"
    grep "^FAIL|" "${CHK}" | sed 's/^FAIL|/  [FAIL] /'
fi
if [ "${CHECK_WARN}" -gt 0 ]; then
    print ""
    print "  *** WARNINGS ***"
    grep "^WARN|" "${CHK}" | sed 's/^WARN|/  [WARN] /'
fi

print ""
print "  Report files:"
print "    Full inventory : ${RPT}"
print "    SVG data       : ${SVG_DATA}"
print "    Check results  : ${CHK}"
print ""
print "  Generated: $(date)"

} 2>&1 | tee "${RPT}"

# ─────────────────────────────────────────────────────────────────────────────
# Generate SVG topology diagram
# ─────────────────────────────────────────────────────────────────────────────
SVG_OUT="${OUTPUT_DIR}/pha_topology_${HOSTNAME}_${TS}.svg"
if [ -x "$(dirname $0)/generate_svg.sh" ]; then
    ksh "$(dirname $0)/generate_svg.sh" "${SVG_DATA}" "${SVG_OUT}"
    print "    SVG topology   : ${SVG_OUT}"
elif [ -x "/usr/local/bin/generate_svg.sh" ]; then
    ksh /usr/local/bin/generate_svg.sh "${SVG_DATA}" "${SVG_OUT}"
    print "    SVG topology   : ${SVG_OUT}"
fi

# ─────────────────────────────────────────────────────────────────────────────
# Exit code: non-zero if any FAIL
# ─────────────────────────────────────────────────────────────────────────────
if [ "${CHECK_FAIL}" -gt 0 ]; then
    exit 2
elif [ "${CHECK_WARN}" -gt 0 ]; then
    exit 1
else
    exit 0
fi
